# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'ELMS(Moodle)',  url: 'https://elms.u-aizu.ac.jp/my/?lang=en'}
- {name: 'Campus square', url: 'https://csweb.u-aizu.ac.jp/campusweb/campusportal.do?locale=en_US'}
- {name: 'Lab home page',       url: 'https://u-aizu.ac.jp/~udayrage/students.html'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'Gmail', link:    'https://mail.google.com/mail/?tab=rm&ogbl'}
- {icon: 'github', link:   'https://github.com/LasyaPalla/Millennial.git'}
- {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
